repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: pipenv run black
    args: [--quiet]
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: pipenv run flake8
    language: system
    types: [python]